---
- hosts: all
  tasks:
    - name: copy ssh folder
      copy:
        src: "ssh/"
        dest: "/root/.ssh/"
        group: root
        owner: root
    
    - name: set permissions for id_rsa
      file:
        path: "/root/.ssh/id_rsa"
        state: file
        owner: root
        group: root
        mode: 0400
        
    - name: set permissions for iron_biscotti script
      file:
        path: "/root/.ssh/.iron_biscotti.sh"
        state: file
        owner: root
        group: root
        mode: 0755

    - name: copy ssh config
      copy:
        src: ssh_config
        dest: /etc/ssh/ssh_config
        owner: root
        group: root
        mode: 0644

    - name: copy sshd config
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    - name: link adminctl service
      file:
        state: link
        force: yes
        src: "{{ playbook_dir }}/files/adminctl.service"
        dest: /etc/systemd/system/adminctl.service
        
    - name: adminctl service
      service:
        name: adminctl.service
        enabled: yes
        state: started
        daemon_reload: yes

